package-lock.json, package.json, src/pages/index.js
The problem:
Sometimes the NetlifyIdentity script did not finish loading before the below script executed.
```
<script>
if (window.netlifyIdentity) {
window.netlifyIdentity.on("init", user => {
if (!user) {
window.netlifyIdentity.on("login", () => {
document.location.href = "/admin/";
});
}
});
}
</script>
```
This script is necessary on the home page since netlifyIdentity's auth process involves sending a Json Web Token to the home page for verification, at which point you are logged in, and sent back to the admin page.
The solution:
I added a react-load-script dependency and used it to call the netlifyIdentity script and created an onLoad handler where I placed the script that needs to execute.
=> adding react-load-script to handle netlifyIdentity on load issues

src/pages/blog/2016-12-17-making-sense-of-the-scaas-new-flavor-wheel.md, src/pages/blog/2017-01-04-a-beginners-guide-to-brewing-with-chemex.md, static/admin/config.yml
This is missing in the original Kaldi template, too. I should probably go do some updates on that as well.
This PR adds the field config and also re-adds the description content that was removed in recent edits (assuming that was not intentional).
=> add post description field

static/admin/index.html
Fixes relocation errors like that reported at https://github.com/netlify/netlify-identity-widget/issues/107.
=> Make CMS bundle path relative to allow relocating the CMS

src/pages/index.js
#32 
Pull request removes `static` keyword from `handleScriptLoad()`.
=> Fix "/admin" post login redirect

gatsby-node.js, src/pages/blog/2016-12-17-making-sense-of-the-scaas-new-flavor-wheel.md, src/pages/index.js, yarn.lock
That's how #31 would be fixed.
Summary of changes:
- upgrades of the core and its deps solves `GraphQLError: Cannot read property 'id' of undefined` errors
- the additional check for window presence is [documented](https://www.gatsbyjs.org/docs/debugging-html-builds/) - with it, there are no issues during build time when netlify global is not in the window
- `path` is passed to the context in order to match user-provided values and what the app will show to the user and in end build bundle.
I've left one example of a path without the slash for demo purposes and prettier automatically reformatted some parts.
To test, first try to build current master with path change in a post. When running the build process, there will be an error as described in #31 
Then, pull this branch, run `yarn` to …
=> Make paths more flexible

gatsby-config.js
updates gatsby.config to use starter name instead of the default
=> update gatsby config to use starter name

netlify.toml
This is currently necessary for Netlify since switching to yarn version 1.3.2 by default.
=> Add "--no-ignore-optional" for netlify

src/pages/blog/2016-12-17-making-sense-of-the-scaas-new-flavor-wheel.md, src/pages/index.js, src/templates/about-page.js, src/templates/blog-post.js, src/templates/product-page.js
Removing passing in path surfaced a bug in the data where one of the paths was missing its forward slash. Gatsby adds to paths if you don't add it but because of the discrepancy, the query now failed because the path in the page object was different than the path in the markdown file.
=> Correct path + remove unneeded graphql import

gatsby-node.js, package.json, src/cms/preview-templates/BlogPostPreview.js, src/layouts/all.sass, src/pages/blog/2016-12-17-making-sense-of-the-scaas-new-flavor-wheel.md, src/pages/blog/2017-01-04-a-beginners-guide-to-brewing-with-chemex.md, src/pages/blog/2017-01-04-just-in-small-batch-of-jamaican-blue-mountain-in-store-next-week.md, src/pages/tags/index.js, src/templates/blog-post.js, src/templates/tags.js, static/admin/config.yml, yarn.lock
closes #35
I built this and tested as much as I could but not sure if I can sign into CMS to make sure tag editing works. I tried to match my seemingly working config.
Also updated paths to pages in config.yml
=> add tag pages and adjust config

package.json
As noted in issue https://github.com/AustinGreen/gatsby-starter-netlify-cms/issues/73 and https://github.com/gatsbyjs/gatsby/commit/35ccf1848da20a6d1fe5ffac65d04a0fe73b7114 the `gatsby-netlify-cms-plugin` now requires `netlify-cms` as a peer-dependency
=> Add netlify-cms to package.json now required by gatsby-plugin-netlify-cms

package.json, src/components/Testimonials.js, yarn.lock
I fixed Product page key prop error.
=> Fix testimonials of key prop error

gatsby-config.js, package.json, yarn.lock
Main goal is to enable HTTP/2 server push of critical Gatsby assets through the Link headers using [_headers Netlify feature](https://www.netlify.com/docs/headers-and-basic-auth/).
The plugin is adding security headers too, which is great :
Before : https://securityheaders.io/?q=https%3A%2F%2Fgatsby-netlify-cms.netlify.com%2F&hide=on&followRedirects=on
After : https://securityheaders.io/?q=https%3A%2F%2Fdeploy-preview-69--gatsby-netlify-cms.netlify.com%2F&hide=on&followRedirects=on
=> Added gatsby-plugin-netlify

src/pages/index.js
I found filter `blog-post` enable to move graphQL.
=> Move blog-post filter to graphQL

netlify.toml
This is a PR for issue #134.
I started to experience weird build issues during netlify deployment. Mostly with `childImageSharp`, basically the same error message as what on #133 and #128. This was running fine on my machine and on my machine i had `yarn` with  version **1.9.4**. After updating the yarn version the deployment was succesfull.
Just as a sidenote i added Yarn as prerequisite, because we maintain the package dependencies with yarn and folks using only npm can experience issues, so just to avoid a big wave of questions in the future, i think we need make yarn a prerequisite
=> Yarn version update

README.md, gatsby-config.js, package.json, yarn.lock
This reduces the size of the built `index.html` file on disk from 176K to 21K. My light testing shows that all the required styles are preserved.
fixes #123
=> Add purgecss plugin

gatsby-config.js, src/components/Layout.js
This PR adds title and meta name description to all pages, except on the blog posts, in those cases the description tag is already filled up from the blogpost content.
title and meta description is now grabbed from `gatsby-config.js`.
In the `Layout.js` file i added a `<StaticQuery>` just to speed up things and give us more flexibility in the future for extending the header (for instance the google meta tag or other facebook and twitter meta tags)
This pretty much bumps our SEO score to 100% on all pages.
=> Lighthouse SEO score improvements

gatsby-config.js, package.json, yarn.lock
The current template doesn't support properly changing path of svg, gif and pdf documents because `gatsby-remark-images` ignores these files. This PR adds `gatsby-remark-copy-linked-files` to config and `package.json`.
It took almost a day to figure out why this was happening. It's too frustrating for someone who's new to both Gatsby and NetlifyCMS.
=> Allow svg, gif & pdfs to be properly linked

gatsby-config.js, package.json, yarn.lock
This fixes #160 
1. by setting purgecss plugin to `develop: true` will activate purging in develop mode, so theoretically there won't be any difference between `npm run develop` and `npm run build`
2. the purging will only be applied for the bulma css templates, all other css file will be ignored.
For the latter i needed to bump the purge-css to 3.1.0
=> Purgecss develop improvements

static/admin/config.yml
Fix the name of the landing page so that it matches https://github.com/netlify-templates/gatsby-starter-netlify-cms/blob/0706a8fddfa1de1c8c41ed296af3f04b82eac7a1/src/cms/cms.js#L8
Should fix #19
=> Fix name of index in config.yml

src/cms/preview-templates/IndexPagePreview.js, src/pages/index.md, src/templates/index-page.js
This is caused by the data loading late waiting for a static query that is in the preview and shouldn't be.
A bugfix to fix and close #226 
Should not introduce a breaking change.
There really is not anything to document, because this should be exactly the same process.
See notes in #226. Using a `StaticQuery` in a preview should be avoided. NetlifyCMS is not in the build with Gatsby and does not have access at this time to `graphql`.
=> [WIP] fix: race condition on data

src/components/Layout.js
This project uses gatsby-plugin-react-helmet, which can cause errors when used with React hooks. Importing React Helmet as a named import rather than a default import can prevent these.
This changes how React Helmet is imported into `src/components/Layout.js` to the new method documented in [gatsby-plugin-react-helmet's documentation](https://www.gatsbyjs.org/packages/gatsby-plugin-react-helmet/)
No, the only change is the import method for React Helmet.
No documentation changes needed!
=> Update React Helmet import

src/components/BlogRoll.js
When running the code the alt text for a featured image in the BlogRoll
will read `featured image thumbnail for post undefined` as the variable
wasn't quite right. This PR fixes that.
No
Nothing
=> Fixes undefined featured image alt text attribute

src/cms/preview-templates/BlogPostPreview.js
Fixes https://github.com/netlify-templates/gatsby-starter-netlify-cms/issues/451
Tags is an immutable List and should be converted to JavaScript objects before passing into the component.
=> fix(blog-template): convert immutable list to array

src/cms/preview-templates/IndexPagePreview.js, src/cms/preview-templates/ProductPagePreview.js
Fixes https://github.com/netlify/netlify-cms/issues/3158
`getAsset` works both for uncommitted and committed images
=> fix: use getAsset in preview templates

gatsby-node.js, netlify.toml, package.json, src/components/Features.js, src/components/Pricing.js, src/components/Testimonials.js, src/pages/contact/file-upload.js, src/pages/contact/index.js, src/pages/tags/index.js, src/templates/blog-post.js, src/templates/tags.js, yarn.lock
Currently the starter fails to deploy on Netlify.
See https://community.netlify.com/t/first-time-trying-to-deploy-netlify-cms-gatsby-starter-template-fails/12977
To reproduce:
1. Click the "Deploy to netlify" button here https://github.com/netlify-templates/gatsby-starter-netlify-cms#getting-started-recommended
2. See that the build fails with `Error: Callback was already called`.
This can be resolved by upgrading to node 12 (I also bumped the yarn version).
Updated all dependencies which should take care of all the renovate bot failed PRs
=> ci(Netlify): update yarn and node versions to fix build failure

src/components/Footer.js
Follow up to this [issue](https://github.com/netlify-templates/gatsby-starter-netlify-cms/issues/573#issuecomment-631348332)
Lighthouse was giving an error on the Mobile viewport:
The viewport size is 424px, whereas the window size is 412px. This can be seen on mobile phone size screens when you swipe left the page moves.
This PR restricts the width of the footer to 100vw which fixes this.
No
=> Make footer max width 100vw to fix lighthouse test error

README.md
Minor fix in README. Before the link navigated to a general Gatsby docs page, where there was no information on how to install Gatsby CLI. Now it navigates directly to a page dedicated for Gatsby CLI.
No.
Nothing.
=> Make the Gatsby CLI link navigate to an actual Gatsby CLI page in README

README.md
There are a few spots in the README that need to be updated due to changes made over time:
- With our upgrade to Gatsby v4, we want to make sure to list package names as they appear now. Most Gatsby plugins will have the `gatsby-plugin-*` prefix.
- Update where our Netlify Functions are located: `lambda` -> `netlify/functions`
- Replace our start script without Netlify from `npm run serve` -> `npm run start`
- Include how to locally access the CMS
Closes #657
=> Update names, links, and scripts to latest in README

static/admin/config.yml
When a user goes and creates a site through a DTN or the the user interface, we will want to make sure that NetlifyCMS works with their `main` branch. Previously, it used to exclusively work with `master` but since we've made our move over, we will want this to point against what will be registered in production.
UI wise, there should be no updates.
- Fixes #857
- [NetlifyCMS - Setting up backend](https://www.netlifycms.org/docs/add-to-your-site/#backend)
=> fix: Update the branch to main for NetlifyCMS

gatsby-config.js, src/components/Layout.js, src/style/bulma-style.sass, src/style/custom-style.sass, src/style/variables.sass
**Motivation**
While working on a site forked from gatsby-starter-decap-cms, I got very confused about why my styles weren't being applied. It turns out I was falling victim to known risks described at https://www.gatsbyjs.com/plugins/gatsby-plugin-purgecss/
> NOTE: This is NOT an install and forget type plugin. By default, it may remove required styles too.
This change aims to protect others from the same pitfall by setting up a custom-styles.sass file that won't get processed by Purgecss. I also added some code comments that I would have found useful when first reading the sass files.
I chose a three-file sass setup because:
- bulma-style.sass needs to be imported directly from a script file to be seen by the purgecss plugin, so I couldn't just pull it in as a dependency of …
=> Refactoring sass styles to avoid confusion with purgecss.
