decaporg/gatsby-starter-decap-cms

src/pages/index.js

Add this so that the netlify log in is not delaying the loading of the site for users.

async netlify identity

---

static/admin/config.yml

fix page paths in config.yml

---

src/cms/preview-templates/AboutPagePreview.js
src/cms/preview-templates/BlogPostPreview.js
src/cms/preview-templates/ProductPagePreview.js
src/components/Content.js
src/components/Features.js
src/components/Pricing.js
src/components/Testimonials.js
src/pages/index.js
src/templates/about-page.js
src/templates/blog-post.js
src/templates/product-page.js

feat(prop-types): add prop-types validation to components

---

src/components/Features.js
src/pages/contact/index.js
src/templates/blog-post.js

Hello everyone!
Firstly, thanks for this project, it's hands down the best way to kickstart a `netlify-cms` powered `gatsby` blog.
While using the template for a recent project I noticed a few console warnings related to `propTypes` and that the blog posts didn't have a `meta` description tag. I thought I should submit a pull request since with changes to address the above since I had to do the same for my project anyways.
Here are screenshots describing each change's effect:
1.  `Features.js`
Console warning on products path related `imageInfo.image` being undefined.
Resolved.
2.  `/contact/index.js`
Console warning on contact path due to `required` attribute's value being string "true".
Resolved.
3. `templates/blog-post.js`
Page displayed a warning suggesting that property `helmet`'s …

Resolve 3 console warnings and add meta description tag to blog posts

---

src/pages/contact/examples.js
src/pages/contact/file-upload.js
src/pages/contact/index.js

Some small improvements:
1. Replaced `navigateTo` with `navigate` (see image)
2. Added link  to a reCAPTCHA implementation in the Troubleshooting section

Contact form improvements

---

src/components/Navbar.js
src/components/all.sass
src/pages/contact/file-upload.js
src/pages/contact/index.js
src/pages/index.js

This PR sets our lighthouse accessibility score to 100 across all pages.
These are mostly minor design changes, it shouldn't break anything.

Lighthouse accessibility improvements

---

src/components/Navbar.js
src/components/all.sass

Hamburger menu is implemented using the Bulma documentation example, along with some small design adjustments. The desktop view remains the same.
This is how it looks
... and after pressing the menu

Navbar mobile view improvements

---

package-lock.json
package.json
yarn.lock

Fixes issue #133 
I had another attempt to bump the version before, but appearantly was unsuccessfull

gatsby-remark-relative-images 0.2.0 -> 0.2.1

---

package-lock.json
yarn.lock

Reverts netlify-templates/gatsby-starter-netlify-cms#181
Webpack broken due to upstream issue with terser.

Revert "Lock file maintenance"

---

src/components/BlogRoll.js

Change `class` to `className`

---

src/components/BlogRoll.js

Warning: validateDOMNesting(...): <p> cannot appear as a descendant of <p>

Fix validateDOMNesting error from nested <p>

---

README.md
_headers
src/components/all.sass

Hi, this PR contains the `_header` file wich has the host header settings for Netlify, plus 1 accessibility fix, which will help us getting to 100 score on Lighthouse accessibility 
It changes the button colors in the index page (Read more, etc), also it helps static assets like images cache in the browser
Normally this shouldn't break anything, except the CI build but we have instant feedback on that 
We could add to the Readme.md that we have 100 scores on SEO, Accessibility on Lighthouse scores!

Netlify Host Headers settings for static assets 

---

src/components/all.sass

Fix an orthografic error

---

src/components/all.sass

This is a replacement for #197
Semicolons in sass files are bothering me, not sure if they were there for a reason but I don't think so :-P
No
Nothing really, just a small bugfix

Remove semicolons from sass file

---

src/components/Navbar.js

This pull request doesn't solve a problem, per se, but I noticed that there was some code from the Bulma website that was manipulating the DOM directly, which kind of defies the whole point of using React, so I replaced it with more React friendly code. 
Minor change in the Navbar Component that replaces direct DOM manipulation with state and a class method
Not that I'm aware of. I'm using the code on a site I'm working on and it's fine.
Nothing, I think. Correct me if I'm wrong.

Replace DOM manipulation in Navbar with State and Class Method

---

gatsby-config.js
src/cms/preview-templates/IndexPagePreview.js
src/components/BlogRoll.js
src/components/Footer.js
src/pages/blog/index.js
src/templates/index-page.js

The changes are resulted by running `yarn format` wich will format the codebase using prettier.
It shouldn't change anything, just formatting
NO.
Nothing.

Reformatting code using prettier

---

package-lock.json
package.json
src/components/Layout.js
src/components/SiteMetadata.js

Use the Gatsby useStaticQuery hook
No breaking changes

Feature/add gatsby useStaticQuery for site metadata

---

src/pages/blog/index.js
src/templates/product-page.js

The hero image seemed to changed position depending on where you were in the site. This adjusts the product and blog template so the hero image matches the landing page.
No.
Nothing.

Make hero image positioning consistant.

---

gatsby-config.js
src/cms/preview-templates/IndexPagePreview.js
src/components/BlogRoll.js
src/components/Navbar.js
src/components/all.sass
src/lambda/hello.js
src/pages/blog/2016-12-17-making-sense-of-the-scaas-new-flavor-wheel.md
src/pages/blog/2017-01-04-a-beginners-guide-to-brewing-with-chemex.md
src/pages/blog/2017-01-04-just-in-small-batch-of-jamaican-blue-mountain-in-store-next-week.md
static/admin/config.yml

Although there is a specific Gatsby blog starter, this starter, with its use of Netlify CMS and main pages, is a more fully-featured personal website, including a blog section. Having the ability to display featured images, certainly in blog post listing sections, is a very common and sought-after function. Additionally, the ability to mark a particular post as 'featured' is also quite common and should be accepted into the standard feature set of any blog setup.
This PR enables the ability to add and update featured meta information into the blog post(s) section of the starter template.
Each of the blog post markdown files can now contain the following two fields within their frontmatter sections: 
- Featured image > 'featuredimage' field …

Featured post meta

---

package.json

https://www.gatsbyjs.org/docs/gatsby-cli/#clean
An improvement
Non-breaking
Not really

Make use of gatsby clean

---

package-lock.json
yarn.lock

Revert "chore(deps): lock file maintenance"

---

src/components/Layout.js

Fix favicon link when pathPrefix is specified

---

README.md
static/admin/config.yml

This PR attempts to improve on the starter's build time. There's two changes in this PR:
1.  Provides explanation on the `README.md` about why and how to remove at least one of the media libraries
2. Adds commit messages to the NetlifyCMS to have a more uniform format of the commit messages and with this be able to skip triggering builds when an image is getting uploaded and deleted. (More explanation below)
[Netlify CMS build improvements on Netlify's forum](https://community.netlify.com/t/common-issue-how-can-i-optimize-my-netlify-build-time/3907/11?u=zltnvrs) by the great @tomrutgers
1. Having one media library will be enough for the usecases the starter is being used. By removing at least one of the media libraries the user can shave off …

Improve build times

---

_headers

TOML content in a _headers file is not allowed and is ignore by production.
Fixes: https://github.com/netlify-templates/gatsby-starter-netlify-cms/issues/545
Fixes: https://github.com/netlify/cli/issues/766
Fixes the `_headers` file syntax.
No.
Nothing

Fix _headers syntax

---

lambda/hello.js

Updates a link in the comments of `lambda/hello.js`, since https://www.netlify.com/docs/functions/#javascript-lambda-functions now redirects to https://www.netlify.com/docs/functions/#javascript-lambda-functions.
No.
N/A.

Update link to JavaScript Lambda functions docs

---

src/components/Navbar.js

Fix eslint warnings.
This is not a breaking change.

fix eslint warnings.

---

package-lock.json
package.json

When a user was installing this project there was an issue with conflicting versions of gatsby and gatsby-plugin-netlify. We're bumping the versions so that way the plugin can handle the latest version of Gatsby!

Updates gatsby-plugin-netlify to ^5.0.0

---

src/components/BlogRoll.js
src/components/Footer.js
src/components/FullWidthImage.js
src/components/Navbar.js
src/templates/tags.js

Refactoring Class based components into Hooks.
Also changes Hamburger menu to a button instead of div and wraps the links in an ul with li's
No
n/a

Refactor to React Hooks 
